'use strict';

/**
 * about-page router
 */

const { createCoreRouter } = require('@strapi/strapi').factories;

// For single types, the 'find' action retrieves the content.
// Other actions like 'update', 'delete' might be generated by default.
// We only need to ensure 'find' is public.
module.exports = createCoreRouter('api::about-page.about-page', {
  config: {
    find: {
      auth: false, // Allow public access to find (get the single type content)
    }
    // update: { auth: false }, // Example if we wanted to make update public
    // delete: { auth: false }, // Example if we wanted to make delete public
  },
});
